# numpy practice session

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
# import this library in j.notebook
import numpy as np

# creating an array using numpy

In [3]:
solanum=np.array(["chacoense", "commersonii", "malmeanum"])
solanum

array(['chacoense', 'commersonii', 'malmeanum'], dtype='<U11')

In [4]:
ploidy = np.array([2,2,2])
ploidy

array([2, 2, 2])

In [5]:
type(ploidy)

numpy.ndarray

In [6]:
type(solanum)

numpy.ndarray

In [7]:
len(solanum)

3

In [12]:
ploidy[0:]

array([2, 2, 2])

In [13]:
solanum[1]

'commersonii'

In [15]:
ploidy.mean()

2.0

In [16]:
# zeros
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [17]:
# ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
# empty
np.empty(5)

array([1., 1., 1., 1., 1.])

In [19]:
# range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# specify
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [24]:
# specific interval
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
# table of 5
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [32]:
# line space
np.linspace(1,10, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [40]:
# specify your data type
np.ones(50, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [38]:
np.ones(50, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# array functions

In [41]:
a = np.array([10, 12, 15, 2, 4, 6, 100, 320, 0.5, 10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.3])

In [42]:
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [44]:
b = np.array([10.2, 3.4, 53.6, 91.6, 45.5])
b

array([10.2,  3.4, 53.6, 91.6, 45.5])

In [45]:
c= np.concatenate((a,b))
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ,  10.2,   3.4,  53.6,  91.6,  45.5])

In [46]:
c.sort()
c

array([  0.5,   2. ,   3.4,   4. ,   6. ,  10. ,  10.2,  10.3,  12. ,
        15. ,  45.5,  53.6,  91.6, 100. , 320. ])

# 2-D array

In [55]:
a= np.array([[1,2], [5,4]])
a

array([[1, 2],
       [5, 4]])

In [56]:
b = np.array([[6,7],[8,9]])
b

array([[6, 7],
       [8, 9]])

In [57]:
c = np.concatenate((a,b), axis=0)
c

array([[1, 2],
       [5, 4],
       [6, 7],
       [8, 9]])

In [58]:
c = np.concatenate((a,b), axis=1)
c

array([[1, 2, 6, 7],
       [5, 4, 8, 9]])

In [59]:
exp = np.array([[[0,1,2,3],
                 [4,5,6,7]],
                
                [[0,1,2,3],
                 [4,5,6,7]],
                
                [[0,1,2,3],
                 [4,5,6,7]]])
exp

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [61]:
# to find the number of dimensions
exp.ndim

3

In [62]:
exp1 = np.array([[5,6,7],
               [8,9,10],
               [10,11,12]])
exp1

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [10, 11, 12]])

In [63]:
exp1.ndim

2

In [64]:
#size ( number of elements)
exp.size

24

In [67]:
#shape
exp.shape

(3, 2, 4)

In [70]:
a = np.arange(9) #3*3=9
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [72]:
#reshape
a = a.reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [73]:
#reshape
np.reshape(a, newshape=(1,9), order='C')

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [74]:
# convert 1D into 2D
a= np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
a.shape

(9,)

In [76]:
#row wise
b= a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [77]:
b.shape

(1, 9)

In [79]:
#column wise
c= a[:, np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [80]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
a[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [83]:
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [84]:
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [86]:
a.sum()

45

In [89]:
a.mean()

5.0